"""fix sender_address typo

Revision ID: 1d4d593a092c
Revises: 094989979811
Create Date: 2025-08-01 21:19:13.594825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4d593a092c'
down_revision: Union[str, Sequence[str], None] = '094989979811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('sender_address', sa.String(), nullable=False))
    op.drop_column('shipments', 'sender_adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('sender_adress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shipments', 'sender_address')
    # ### end Alembic commands ###
