name: FastAPI Shipment Test

on:
  workflow_dispatch: ## will change it when the bug is fixed. 'alembic'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image:
          postgres:15
        env:
          POSTGRES_DB: shipping
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h db -U postgres && break
            sleep 5
          done

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest